name: Deploy

on:
  push:
    branches: [ main ]

jobs:

  Deploy:

    name: Deploy
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '+ DEPLOY')"

    steps:

      - name: Mark as successful run
        run: |
          true
